apiVersion: v1
kind: Namespace
metadata:
  name: colis-dev
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: c3mweb-lpmin
  namespace: colis-dev
  labels:
    app: c3mweb-lpmin
spec:
  replicas: 3 #We always want more than 1 replica for HA test
  selector:
    matchLabels:
      app: c3mweb-lpmin
  template:
    metadata:
      labels:
        app: c3mweb-lpmin
    spec:
      volumes:
        - name: template-volume
          persistentVolumeClaim:
            claimName: c3m-grpc-lptpl-pvc
      containers:
        - name: c3mweb-lpmin #1st container
          image: tidusant/c3mweb-lpmin:latest #Dockerhub image
          volumeMounts:
            - mountPath: /app/templates
              name: template-volume
          ports:
            - containerPort: 8090 #Exposes the port of the container
          env:
            - name: API_URL
              value: "http://c3m-api-service:8081/"
          
         
---
kind: Service
apiVersion: v1
metadata:
  name: c3mweb-lpmin-service
  namespace: colis-dev
spec:
  type: NodePort
  selector:
    app: c3mweb-lpmin
  ports:
    - name: c3mweb-lpmin-port
      protocol: TCP
      port: 8090
      nodePort: 30090 #must be between 30000 - 32767
  