# This is a basic workflow to help you get started with Actions

name: Dev Deployment
env:
  SERVER: colis-dev
  PREFIX: c3mweb
  COMMIT_FILTER: DEPLOY
  API_URL: ${{ secrets.API_URL }}
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch  
  push:
#    branches: [ master ]
    paths-ignore:
    #- '.github/**'
    - 'README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
       
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      isdeploy: ${{steps.checkdeploy.outputs.isdeploy}}
      apppath: ${{steps.checkdeploy.outputs.apppath}}  
      appname: ${{steps.checkdeploy.outputs.appname}}  
      branch: ${{steps.checkdeploy.outputs.branch}}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - id: checkdeploy
        name: check is Deploy    
        run: | 
          echo ${GITHUB_EVENT_PATH}
          echo ${GITHUB_WORKSPACE}
          #Set branch name
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
          # Get last commit message
          readonly local last_commit_log="${{github.event.head_commit.message}}"
          echo "last commit log: $last_commit_log"
          
          #readonly local result=$(echo "$last_commit_log" | grep -E "^${COMMIT_FILTER}" )
          readonly local result1=$(echo "$last_commit_log" | cut -d" " -f1 )
          readonly local result2=$(echo "$last_commit_log" | cut -d" " -f2 )

          if [ "$result1" == ${COMMIT_FILTER} ]; then            
            echo "the last commit log contains \"$COMMIT_FILTER\", start building"            
            echo "::set-output name=isdeploy::true"
            echo "::set-output name=apppath::$result2"
            echo "::set-output name=appname::${result2//\//\-}"
          else            
            echo "not a DEPLOY command"
            echo "::set-output name=isdeploy::false"
          fi    
  
      - uses: actions/checkout@v2
      - name: test
        if: ${{ contains(steps.checkdeploy.outputs.isdeploy, 'true') }}     
        run: | 
          cd ${{steps.checkdeploy.outputs.apppath}}
          npm install
          npm test
      - name: build
        if: ${{ contains(steps.checkdeploy.outputs.isdeploy, 'true') }}
        run: | 
          cd ${{steps.checkdeploy.outputs.apppath}}
          echo "====== Docker build ========"
          echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
          docker build -t ${{steps.checkdeploy.outputs.appname}} .
          docker tag ${{steps.checkdeploy.outputs.appname}} ${{ secrets.DOCKER_USERNAME }}/${PREFIX}-${{steps.checkdeploy.outputs.appname}}
          docker push ${{ secrets.DOCKER_USERNAME }}/${PREFIX}-${{steps.checkdeploy.outputs.appname}}
          
  deploy:
    if: ${{ contains(needs.check.outputs.isdeploy, 'true') }}
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [check]
    steps:
    - name: Kubernetes deploy
      run: |
        sudo kubectl apply -f https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${{needs.check.outputs.branch}}/${{needs.check.outputs.apppath}}/k8s_devdeploy.yml
        #force pull latest image
        sudo kubectl -n ${SERVER} rollout restart deploy ${PREFIX}-${{needs.check.outputs.appname}}
